// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5gbrb2yBDSRWrldo4D9gKqnnFldM1Mo',
    appId: '1:225344594013:web:e9b476d98d6910d1f3edb4',
    messagingSenderId: '225344594013',
    projectId: 'ai-study-app-a19c3',
    authDomain: 'ai-study-app-a19c3.firebaseapp.com',
    storageBucket: 'ai-study-app-a19c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexwubSKozjfGwKahjmFtSB6X6nJnFIAw',
    appId: '1:225344594013:ios:c726d300040fdc17f3edb4',
    messagingSenderId: '225344594013',
    projectId: 'ai-study-app-a19c3',
    storageBucket: 'ai-study-app-a19c3.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexwubSKozjfGwKahjmFtSB6X6nJnFIAw',
    appId: '1:225344594013:ios:c726d300040fdc17f3edb4',
    messagingSenderId: '225344594013',
    projectId: 'ai-study-app-a19c3',
    storageBucket: 'ai-study-app-a19c3.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy5gbrb2yBDSRWrldo4D9gKqnnFldM1Mo',
    appId: '1:225344594013:web:a3a74ea82ab0c34ff3edb4',
    messagingSenderId: '225344594013',
    projectId: 'ai-study-app-a19c3',
    authDomain: 'ai-study-app-a19c3.firebaseapp.com',
    storageBucket: 'ai-study-app-a19c3.firebasestorage.app',
  );
}
